# terraform-docs configuration
# https://terraform-docs.io/user-guide/configuration/

formatter: markdown table

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {% raw %}{{ .Header }}{% endraw %}

  ## Usage

  ```hcl
  {% raw %}{{ include "examples/basic/main.tf" }}{% endraw %}
  ```

  {% raw %}{{ .Requirements }}{% endraw %}

  {% raw %}{{ .Providers }}{% endraw %}

  {% raw %}{{ .Modules }}{% endraw %}

  {% raw %}{{ .Resources }}{% endraw %}

  {% raw %}{{ .Inputs }}{% endraw %}

  {% raw %}{{ .Outputs }}{% endraw %}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {% raw %}{{ .Content }}{% endraw %}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
