# Markdownlint configuration
# https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md

# MD013 - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033 - Inline HTML
MD033: false

# MD041 - First line in file should be a top level header
MD041: false
